package org.example;
    dialect "java"

import org.optaplanner.core.api.score.buildin.simple.SimpleScoreHolder;
import org.example.Item;
import org.example.Bucket;

global SimpleScoreHolder scoreHolder;

// ############################################################################
// Calculate score
// ############################################################################

rule "calculate score"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $total : Number(intValue >0 ) from accumulate(
            Item($price : price, inCart == true),
            sum($price)
        )
    then
//    	System.out.println("total = " + $total.intValue());
        scoreHolder.setScore(-Math.abs($total.intValue() - 11000));
end
